### ISSUE TITLE
Incorrect statistics in QOS

### ISSUE THREAD

**Issue by JonasNorlinder** [bubify/bubify-backend#1]
QOS is not filtering on claimed students anymore. We only want to count students who are waiting a teacher to claim their request.

**Comment by Olofasenius** [comment]
Code snippet found in DemonstrationController.java, in method "pending"

´´´
javax.persistence.criteria.Predicate isActiveAndSubmittedOrClaimed = criteriaBuilder.and(
                criteriaBuilder.or(
                        criteriaBuilder.equal(root.get("status"), DemonstrationStatus.SUBMITTED),
                        criteriaBuilder.equal(root.get("status"), DemonstrationStatus.CLAIMED)
                ),
                criteriaBuilder.greaterThan(root.get("requestTime"), nowMinus24Hours)
        );
        criteriaQuery.select(root).where(isActiveAndSubmittedOrClaimed);
        var list = entityManager.createQuery(criteriaQuery).getResultList();
´´´


submitted Or claimed could maybe be the cause of the problem?
